export const inputsData = [
	{
		id: "title",
		errorMessage: "The field cannot be empty",
		required: true,
		label: "Title",
		type: "text",
		id: "title",
		name: "title",
	},
	{
		errorMessage: "The field cannot be empty",
		required: true,
		label: "Enter the address",
		type: "text",
		id: "address",
		name: "address",
	},
	{
		errorMessage: "The field cannot be empty",
		required: true,
		label: "Full Name",
		type: "text",
		id: "fullName",
		name: "fullName",
	},
	{
		id: "jobPosition",
		errorMessage: "The field cannot be empty",
		required: true,
		label: "Job Position",
		type: "text",
		name: "jobPosition",
	},
	{
		errorMessage: "Email should be a valid email address",
		required: true,
		label: "Email Address",
		type: "email",
		id: "email",
		name: "email",
		placeholder: "name@example.com",
		pattern: "^[^@]+@[^@]+.[^@]+$",
	},
	{
		errorMessage: "Phone should be a valid phone number",
		required: true,
		label: "Phone",
		type: "tel",
		id: "phone",
		name: "phone",
		placeholder: "(xxx) xxx-xxxx",
		pattern: "^(+d{1,2}s?)?1?-?.?s?(?d{3})?[s.-]?d{3}[s.-]?d{4}$",
	},
];

export const defaultInputData = {
	title: "",
	address: "",
	fullName: "",
	jobPosition: "",
	email: "",
	phone: "",
};

export const locationMockData = [
	{
		title: "Pane",
		address: "U Náhonu 1379",
		fullName: "Šťasta Brazda",
		jobPosition: "Chirurg",
		email: "allied1816@live.com",
		phone: "0133",
		id: 1,
	},
	{
		title: "Paní",
		address: "Jánská 294",
		fullName: "Adriena Sedlak",
		jobPosition: "Průmyslový designér",
		email: "senators1879@outlook.com",
		phone: "9507",
		id: 2,
	},
	{
		title: "JUDr.",
		address: "Náměstí 5.Května 461",
		fullName: "Zbyslav Wotruba",
		jobPosition: "Specialista pohledávek",
		email: "gambling2055@example.com",
		phone: "2988",
		id: 3,
	},
	{
		title: "CSc.",
		address: "U Zdravotního Střediska 913",
		fullName: "Adolfína Sobotka",
		jobPosition: "Vedoucí výroby",
		email: "knit1807@gmail.com",
		phone: "5120",
		id: 4,
	},
	{
		title: "Ing.",
		address: "Dr. Buděšínského 557",
		fullName: "Barnabáš Strnad",
		jobPosition: "Řidič",
		email: "resistance1832@duck.com",
		phone: "3710",
		id: 5,
	},
	{
		title: "PharmDr.",
		address: "Jílovská 966",
		fullName: "Darja Řezník",
		jobPosition: "Personalista",
		email: "released2000@gmail.com",
		phone: "2202",
		id: 6,
	},
	{
		title: "Ing. arch.",
		address: "Náměstí Dr. Karla Kramáře 680",
		fullName: "Justýna Vydra",
		jobPosition: "Mechanik",
		email: "retirement1828@protonmail.com",
		phone: "9589",
		id: 7,
	},
	{
		title: "Paní",
		address: "Na Brodech 1253",
		fullName: "Ludoslava Havelka",
		jobPosition: "Speciální pedagog",
		email: "times2058@example.com",
		phone: "0726",
		id: 8,
	},
	{
		title: "Th.D.",
		address: "U Špejcharu 704",
		fullName: "Tibor Květoň",
		jobPosition: "Elektromontér",
		email: "meaningful1871@gmail.com",
		phone: "2061",
		id: 9,
	},
	{
		title: "Mgr.",
		address: "Na Pahrbku 51",
		fullName: "Eulálie Kožený",
		jobPosition: "Technik dopravy",
		email: "remove1989@example.com",
		phone: "5839",
		id: 10,
	},
	{
		title: "BcA.",
		address: "V Horce 434",
		fullName: "Zlatuše Valenta",
		jobPosition: "Keramik",
		email: "speeds1855@duck.com",
		phone: "9653",
		id: 11,
	},
	{
		title: "DrSc.",
		address: "Ondříčkova 657",
		fullName: "Arzen Toman",
		jobPosition: "Tiskař",
		email: "hull1876@yandex.com",
		phone: "4443",
		id: 12,
	},
	{
		title: "Paní",
		address: "Ve Slévi 923",
		fullName: "Oswald Valenta",
		jobPosition: "Specialista mobilních technologií",
		email: "relaxation2099@example.org",
		phone: "4653",
		id: 13,
	},
	{
		title: "Th.D.",
		address: "Ke Školce 330",
		fullName: "Kašpar Tomíčková",
		jobPosition: "Speciální pedagog",
		email: "brilliant2027@outlook.com",
		phone: "9417",
		id: 14,
	},
	{
		title: "Pane",
		address: "Pampelišková 635",
		fullName: "Adrian Krejčír",
		jobPosition: "Účetní",
		email: "blocking1924@protonmail.com",
		phone: "8740",
		id: 15,
	},
	{
		title: "Pane",
		address: "Šachetní 327",
		fullName: "Erich Janda",
		jobPosition: "Technik ve strojírenství",
		email: "cigarette1802@outlook.com",
		phone: "5545",
		id: 16,
	},
	{
		title: "Th.D.",
		address: "Oblanovská 763",
		fullName: "Radek Nedvěd",
		jobPosition: "Obchodní referent",
		email: "wordpress1993@outlook.com",
		phone: "8896",
		id: 17,
	},
	{
		title: "CSc.",
		address: "K Ohradám 876",
		fullName: "Hanuš Hrdlička",
		jobPosition: "Námořník",
		email: "citizen1862@live.com",
		phone: "0158",
		id: 18,
	},
	{
		title: "Pane",
		address: "Osada Spálený 216",
		fullName: "Melita Zvěřinová",
		jobPosition: "Makléř",
		email: "qualification1903@duck.com",
		phone: "2801",
		id: 19,
	},
	{
		title: "Pane",
		address: "Zeyerovo Náměstí 1300",
		fullName: "Josselin Kubicki",
		jobPosition: "Finanční kontrolor",
		email: "deviation1959@yahoo.com",
		phone: "3274",
		id: 20,
	},
];
